resources:
  - name: find-buckfast
    type: git
    source:
      uri: https://github.com/seadowg/find-buckfast.git
      branch: master

jobs:
  - name: test
    build: find-buckfast/test.yml
    inputs:
      - resource: find-buckfast

  - name: deploy
    build: find-buckfast/deploy.yml
    inputs:
      - resource: find-buckfast
        passed: [test]
